Test: OCR Service, PDF Service 테스트 추가
29ana-notai/Team29_BE pull request #21
Opened 2024-10-15 02:51 UTC by yunjunghun0116

테스트코드 추가

2024-10-15 04:10 UTC, hynseoj approved these changes
고생하셨습니다!
pr 보내는 브랜치 Weekly8 으로 변경해주실 수 있으실까요 🥹

2024-10-15 11:30 UTC, yunjunghun0116 commented
> 고생하셨습니다! pr 보내는 브랜치 Weekly8 으로 변경해주실 수 있으실까요 🥹

넵! 변경했습니다 :)

2024-10-25 08:01 UTC, rladbrua0207 requested changes
고생하셨습니다! 

@tag("exclude-test")만 통합테스트 파일에 추가해주시면 수락하겠습니다!

2024-10-25 08:01 UTC, rladbrua0207 commented on src/test/java/notai/pdf/PdfServiceTest.java
로컬에 있는 파일 가지고 테스트하는거라 아마 빌드할때 테스트 통과 못해서 빌드 실패할 것 같습니다

@Tag("exclude-test")  추가해주실 수 있나요?


그리고 deleteFile(filePath); 이 메서드는 저번에 지우시겠다고 하셨던거로 기억합니다!

2024-10-25 10:12 UTC, yunjunghun0116 commented on src/test/java/notai/pdf/PdfServiceTest.java
넵 추가했습니다! 추가하니 확실히 모두가 테스트 실행 시 성공적으로 동작할 수  있겠더라고요!
또한 현재로서는 불필요한 PDF Service Test 를 삭제하였습니다!

2024-10-25 12:15 UTC, rladbrua0207 commented on src/test/java/notai/pdf/PdfServiceTest.java
감사합니다! 고생하셨습니다~!

2024-10-25 12:16 UTC, rladbrua0207 approved these changes

2024-10-25 12:16 UTC, merged