Refactor: Document, Folder 이슈 해결
29ana-notai/Team29_BE pull request #28
Opened 2024-10-31 03:24 UTC by yunjunghun0116

## 작업 내용

- Document의 조회 시 루트폴더의 ID를 null 이 아닌 -1 이라는 값을 static 으로 추출하여 비교하도록 설정
- Document save 과정에서 src/main/resources 폴더가 아닌 다른 로컬 폴더를 사용하도록 변경
- 요청시 주고받을 수 있는 용량 1MB 에서 10MB로 확장

## Merge 시 요구사항

- 테스트 코드를 보면 Document 를 생성할 때, Member를 추가하도록 변경하였습니다. 그 이유는 이용자의 루트 폴더에 해당하는 문서를 조회할 때 폴더ID는 -1로 고정이기 때문인데, 이러한 문제를 MemberId와 FolderIdIsNull 를 통해 해결하고자 접근하였기 때문에 이 부분에 대해 확인하시고 테스트코드 중 기존 Document 생성자에 대해 member 객체를 추가해주시면 감사할 것 같습니다!

2024-10-31 04:00 UTC, rladbrua0207 requested changes
고생하셨습니다!


포메팅 부분이랑 application.yml에서 STORAGE_DIR 관리하는 방식으로 하는게 좋을 것 같아서 확인해주시면 좋을 것 같습니다.

2024-10-31 04:00 UTC, yugyeom-ghim commented on src/main/java/notai/common/config/AuthConfig.java
이부분은 포메팅이 Line breaks가 체크가 안돼있어서 자동 줄바꿈 해제된 것 같습니다

2024-10-31 04:00 UTC, yugyeom-ghim commented on src/main/java/notai/pdf/PdfService.java
로컬환경, 배포환경에서 다를 것 같아서 STORAGE_DIR은 @Value로 application.yml에서 관리해주는게 좋을 것 같아요

2024-10-31 06:30 UTC, hynseoj approved these changes
고생하셨습니다!! 그리고 document 에 member 추가하신 김에 소유 검증하는 메서드도 나중에 작성 부탁드립니다!
documentId 로 접근하는 api 에 다 검증을 추가해야할 것 같아서요!!

2024-10-31 14:20 UTC, yugyeom-ghim commented on src/main/java/notai/ocr/application/OCRService.java
이부분도 경로를 따로 @Value로 관리하면 배포환경에서 다르게 설정하기 좋을 것 같아요

2024-10-31 14:24 UTC, rladbrua0207 commented on src/main/java/notai/ocr/application/OCRService.java
제가 배포중이라서 이부분은 제가 변경해서 PR날려두겠습니다!

2024-11-01 13:26 UTC, rladbrua0207 approved these changes

2024-11-01 13:26 UTC, merged